spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1        # Redis服务器地址 ‌:ml-citation{ref="5,7" data="citationList"}
    port: 6379            # 默认端口号 ‌:ml-citation{ref="5,7" data="citationList"}
    password: 123456    # 密码（未设置可省略） ‌:ml-citation{ref="5,7" data="citationList"}
    database: 0           # 数据库索引（默认0） ‌:ml-citation{ref="7,8" data="citationList"}
    timeout: 2000

mybatis:
  mapper-locations: classpath:mapper/*.xml  # MyBatis XML路径
  configuration:
    map-underscore-to-camel-case: true     # 字段自动驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印SQL语句
  type-aliases-package: com.example.ecommerce.entity  # 别名包

